import { Claim, ClaimStatus, LocationType, AccidentType, VehicleType } from "./types";

export const APP_NAME = "IMVC-DES";
export const APP_VERSION = "1.0.0-beta";

export const SEED_CLAIMS: Claim[] = [
  {
    id: "CLM-20240126-001",
    userId: "u1",
    status: ClaimStatus.APPROVED,
    createdAt: "2024-01-20T10:00:00Z",
    policyNumber: "POL-88392-X",
    policyExpiryDate: "2025-06-30",
    daysToExpiry: 160,
    claimablePolicy: true,
    incidentDetails: {
      accidentDate: "2024-01-19",
      accidentTime: "14:30",
      locationType: LocationType.CITY,
      description: "Rear-ended at a traffic light.",
    },
    vehicleDetails: {
      registrationNumber: "MH-02-AZ-9999",
      insurerName: "SafeGuard Insure",
      vehicleType: VehicleType.FOUR_WHEELER,
      carAge: 3,
    },
    accidentSpecifics: {
      accidentType: AccidentType.COLLISION,
      damageParts: ["rear_bumper", "trunk"],
      previousClaims: 0,
      policeReport: false,
      driverAtFault: false,
      driverAge: 34,
      driverLicenseValid: true,
      alcoholIntoxicated: false,
    },
    images: [{ id: "img1", url: "https://picsum.photos/400/300?random=1", type: "image/jpeg" }],
    aiAnalysis: {
      damagePercent: 22.5,
      confidence: 0.98,
      approvalProbability: 0.95,
      explanations: [
        "Clear rear impact damage consistent with description.",
        "Policy active and coverage includes collisions.",
      ],
      ragMatches: [
        {
          text: "Collision coverage includes rear-end impacts regardless of fault if third-party identified.",
          source: "Policy_Doc_v2.pdf",
          page: 14,
          score: 0.92,
        },
      ],
    },
  },
  {
    id: "CLM-20240125-042",
    userId: "u1",
    status: ClaimStatus.REJECTED,
    createdAt: "2024-01-18T09:15:00Z",
    policyNumber: "POL-11223-Y",
    policyExpiryDate: "2023-12-31",
    daysToExpiry: -18,
    claimablePolicy: false,
    incidentDetails: {
      accidentDate: "2024-01-18",
      accidentTime: "09:00",
      locationType: LocationType.HIGHWAY,
      description: "Hit a guardrail.",
    },
    vehicleDetails: {
      registrationNumber: "KA-05-MM-1234",
      insurerName: "SafeGuard Insure",
      vehicleType: VehicleType.FOUR_WHEELER,
      carAge: 8,
    },
    accidentSpecifics: {
      accidentType: AccidentType.COLLISION,
      damageParts: ["front_right"],
      previousClaims: 2,
      policeReport: true,
      driverAtFault: true,
      driverAge: 22,
      driverLicenseValid: true,
      alcoholIntoxicated: false,
    },
    images: [],
    aiAnalysis: {
      damagePercent: 45.0,
      confidence: 0.89,
      approvalProbability: 0.01,
      explanations: ["Policy expired 18 days prior to incident.", "Clause 2.1 excludes coverage for expired policies."],
      ragMatches: [
        {
          text: "Claims must be filed within the active policy period.",
          source: "Terms_Conditions.pdf",
          page: 2,
          score: 0.99,
        },
      ],
    },
  },
  {
    id: "CLM-20240127-003",
    userId: "u1",
    status: ClaimStatus.REJECTED,
    createdAt: "2024-01-26T14:20:00Z",
    policyNumber: "POL-7733-Z",
    policyExpiryDate: "2024-09-15",
    daysToExpiry: 230,
    claimablePolicy: true,
    incidentDetails: {
      accidentDate: "2024-01-26",
      accidentTime: "11:00",
      locationType: LocationType.RURAL,
      description: "Tree branch fell on roof during storm.",
    },
    vehicleDetails: {
      registrationNumber: "DL-3C-CC-4545",
      vehicleType: VehicleType.FOUR_WHEELER,
      insurerName: "SafeGuard Insure",
      carAge: 1,
    },
    accidentSpecifics: {
      accidentType: AccidentType.NATURAL_DISASTER,
      damageParts: ["roof", "windshield"],
      previousClaims: 0,
      policeReport: false,
      driverAtFault: false,
      driverAge: 40,
      driverLicenseValid: true,
      alcoholIntoxicated: false,
    },
    images: [{ id: "img2", url: "https://picsum.photos/400/300?random=2", type: "image/jpeg" }],
    aiAnalysis: undefined,
  },
  {
    id: "CLM-20240201-010",
    userId: "u2",
    status: ClaimStatus.PENDING,
    createdAt: "2024-01-31T09:00:00Z",
    policyNumber: "POL-99001-A",
    policyExpiryDate: "2026-02-01",
    daysToExpiry: 365,
    claimablePolicy: true,
    incidentDetails: {
      accidentDate: "2024-01-31",
      accidentTime: "08:15",
      locationType: LocationType.CITY,
      description: "Side mirror clipped by passing vehicle.",
    },
    vehicleDetails: {
      registrationNumber: "MH-12-XY-4321",
      insurerName: "UrbanCover",
      vehicleType: VehicleType.TWO_WHEELER,
      carAge: 2,
    },
    accidentSpecifics: {
      accidentType: AccidentType.COLLISION,
      damageParts: ["mirror"],
      previousClaims: 0,
      policeReport: false,
      driverAtFault: false,
      driverAge: 28,
      driverLicenseValid: true,
      alcoholIntoxicated: false,
    },
    images: [{ id: "img10", url: "https://picsum.photos/400/300?random=10", type: "image/jpeg" }],
    aiAnalysis: {
      damagePercent: 5.0,
      confidence: 0.7,
      approvalProbability: 0.9,
      explanations: ["Minor mirror damage; likely cosmetic."],
      ragMatches: [],
    },
  },
  {
    id: "CLM-20240202-011",
    userId: "u3",
    status: ClaimStatus.ANALYZING,
    createdAt: "2024-02-01T11:30:00Z",
    policyNumber: "POL-55522-B",
    policyExpiryDate: "2025-05-20",
    daysToExpiry: 474,
    claimablePolicy: true,
    incidentDetails: {
      accidentDate: "2024-02-01",
      accidentTime: "11:00",
      locationType: LocationType.HIGHWAY,
      description: "Tire burst caused spin out.",
    },
    vehicleDetails: {
      registrationNumber: "KA-07-GH-2020",
      insurerName: "DriveSafe",
      vehicleType: VehicleType.FOUR_WHEELER,
      carAge: 6,
    },
    accidentSpecifics: {
      accidentType: AccidentType.SLIP,
      damageParts: ["left_tire", "rim"],
      previousClaims: 1,
      policeReport: false,
      driverAtFault: false,
      driverAge: 45,
      driverLicenseValid: true,
      alcoholIntoxicated: false,
    },
    images: [],
    aiAnalysis: {
      damagePercent: 30.0,
      confidence: 0.6,
      approvalProbability: 0.5,
      explanations: ["Mechanical failure suspected; requires manual review."],
      ragMatches: [],
    },
  },
  {
    id: "CLM-20240203-012",
    userId: "u4",
    status: ClaimStatus.REQUIRES_REVIEW,
    createdAt: "2024-02-02T16:05:00Z",
    policyNumber: "POL-33110-C",
    policyExpiryDate: "2024-12-31",
    daysToExpiry: 334,
    claimablePolicy: true,
    incidentDetails: {
      accidentDate: "2024-02-02",
      accidentTime: "15:50",
      locationType: LocationType.CITY,
      description: "Minor fire in engine compartment.",
    },
    vehicleDetails: {
      registrationNumber: "DL-1A-BC-9876",
      insurerName: "FireShield",
      vehicleType: VehicleType.TRUCK,
      carAge: 10,
    },
    accidentSpecifics: {
      accidentType: AccidentType.FIRE,
      damageParts: ["engine", "front_body"],
      previousClaims: 2,
      policeReport: true,
      driverAtFault: true,
      driverAge: 38,
      driverLicenseValid: true,
      alcoholIntoxicated: false,
      witnessName: "Ravi Sharma",
    },
    images: [{ id: "img12", url: "https://picsum.photos/400/300?random=12", type: "image/jpeg" }],
    aiAnalysis: {
      damagePercent: 80.0,
      confidence: 0.95,
      approvalProbability: 0.02,
      explanations: ["Severe engine damage; high likelihood of total loss."],
      ragMatches: [],
    },
  },
];

export const SAMPLE_USER = {
  id: "u1",
  name: "Alex Morgan",
  email: "alex.morgan@company.com",
  role: "user" as const,
  company: "Logistics Corp",
  avatar: "https://picsum.photos/200/200?random=user",
};
